application: dbplanview
version: 1
runtime: python
api_version: 1

handlers:
- url: /(index.html)?
  static_files: jsplanview/planview.html
  upload: jsplanview/planview.html

- url: /(.+)
  static_files: jsplanview/\1
  upload: jsplanview/(.+)

